### ISSUE TITLE
How to use this bot for a dumb beginner

### ISSUE THREAD

**Issue by nazmifr** [brettstimmerman/jabber-bot#11]
Hi, this is not really an issue but more me being a newbie, but I can't find any ressources, I've never heard of ruby gems in the past, I'm documenting myself but I'm no dev.

Could you help me understand how to install and get this bot to work ? I've installed rubygems (I'm under devuan jessie GNU/Linux) and also I found jabber::simple (aka xmpp4-something) and git cloned the two repositories, I then tried a lot of ruby commands: 
ruby build 
ruby rake
...
but  I just don't get it. What do I need to do to build from the sources ?

Thanks in advance for any help.

**Comment by brettstimmerman** [comment]
Hi @nazmifr,

I admit the jabber-bot README could be a little more useful. How about you and I make it better for the next folks who find it?

To run your own bot you shouldn't need to `git clone` anything, or build anything from sources. If you've got RubyGems installed, you're already only a few keystrokes away from having a running bot!

From here, the quickest way to create a bot would probably be to get the sample bot up and running:
1. Run `gem install jabber-bot xmpp4r-simple` to install the gems onto your computer
1. Copy the source of the [sample bot](https://raw.githubusercontent.com/brettstimmerman/jabber-bot/master/sample/sample.rb) and paste it into a new file on your computer, for example `test_bot.rb`
1. Edit the `config` Hash of the bot file (lines  35-44) as needed, especially the values for the bot's `jabber_id` and `password`, and the `master` account, which is another jabber id authorized to give the bot commands
1. Start the bot: `ruby path/to/test_bot.rb`.

If all goes well, the bot should send its master a jabber message like `PublicBot reporting for duty.` The `master` can then send commands to the bot with messages. For example when the message is `puts hello world`, the sample bot should write `master says 'hello world'` to stdout where the bot was started and reply with the message `'hello world' written to $stdout`. When the message is `rand`, the sample bot should reply with a random number from `0` to `10`.

Let me know if you get stuck along the way and I'll try to help.

**Comment by brettstimmerman** [comment]
Hi @nazmifr, Since I haven't heard back from you, I assume you no longer need help.

**Comment by nazmifr** [comment]
Hi, 
Sorry I had to go abroad and had no access to my mails until today and no internet access until a few days ago, so I didn't see your response, I read your detailled description of the process and think I understood how it works and where I was doing it all wrong (with the git clone and the ruby upgrade and whatever weird stuff I was trying).

I don't have internet on my main GNU/Linux PC for the moment so I can't test it now, but I'll be back home in a week, thank you for the time you took to write all of that and sorry not to have responded before :/ of course I'll post feedback on how it all went once I've tested it, in case you still want to make the readme more clear.

**Comment by nazmifr** [comment]
@brettstimmerman brettstimmerman 

Thanks for your tutorial, I recovered access to my main machine and tried, it kinda works, I mean, after some work (I managed to get the script to work (apparently there are some errors in xmpp4r-simple's files, ":" instead of ";" when instead of then and such, so I tried stuff and there is no error anymore:

ruby bot.rb
```
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': /var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:441: syntax error, unexpected ':', expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
                   when nil: new_presence.show || :online
                            ^
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:442: syntax error, unexpected keyword_when, expecting keyword_end
                   when :unavailable: :unavailable
                       ^
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:443: syntax error, unexpected keyword_else, expecting keyword_end
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:490: syntax error, unexpected keyword_end, expecting end-of-input
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/jabber-bot-1.3.0/lib/jabber/bot.rb:30:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from glimmy.rb:32:in `<main>'
```

I changed

```        simple_jid = roster_item.jid.strip.to_s
        presence = case new_presence.type
                   when nil: new_presence.show || :online
                   when :unavailable: :unavailable
                   else
                     nil
                   end
```
to 
```
       presence = case new_presence.type
                   when nil
		   then new_presence.show || :online
                   #when :unavailable
		   #then new_presence.show || :unavailable
                   else
                     nil
                   end
```

and the error is gone, now it loads forever and then gives back the input in command line, I tried 

ruby -v bot.rb

and got:
```
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:392: warning: assigned but unused variable - jid
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:408: warning: assigned but unused variable - e
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:413: warning: assigned but unused variable - client
/var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:494: warning: possibly useless use of true in void context
/var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:354: warning: assigned but unused variable - err
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55: warning: loading in progress, circular require considered harmful - /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/iq.rb
        from glimmy.rb:32:in  `<main>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in  `rescue in require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in  `require'
        from /var/lib/gems/2.1.0/gems/jabber-bot-1.3.0/lib/jabber/bot.rb:30:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:19:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r.rb:116:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/xmpp4r.rb:14:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/client.rb:6:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/connection.rb:9:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/stream.rb:12:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/iq.rb:10:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/vcard/iq/vcard.rb:5:in  `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in  `require'
/var/lib/gems/2.1.0/gems/xmpp4r-0.5.6/lib/xmpp4r/reliable.rb:77: warning: assigned but unused variable - e

```

Do you have any insight on that ? I'm no dev I might have fucked up the xmpp4r-simple file with my edits, I also tried to update xmpp4r-simple without success.

Thanks already for your help and in advance in case you can help me further.

**Comment by nazmifr** [comment]
I tried with another account, the bot connected apparently and added me on jabber, it doesn't answer to commands, the stdout works however:

```
 /var/lib/gems/2.1.0/gems/xmpp4r-simple-0.8.8/lib/xmpp4r-simple.rb:305: warning: instance variable @accept_subscriptions not initialized
nazmifr@jappix.com says 'dd'
nazmifr@jappix.com says '"eeeeejhsqçibh edhfsdphf"'
nazmifr@jappix.com says 'hello world'
```

though I'm not receiving messages

Do you have any insight ?
